// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace accomondationApp.AuthModel;

public partial class LoginModel
{
    public long Id { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string RefreshToken { get; set; }

    public DateTime RefreshTokenExpiryTime { get; set; }

    public virtual ICollection<UserInRole> UserInRoles { get; set; } = new List<UserInRole>();
}