// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace accomondationApp.AuthModel;

public partial class Role
{
    public int RoleId { get; set; }

    public string Role1 { get; set; }

    public virtual ICollection<UserInRole> UserInRoles { get; set; } = new List<UserInRole>();
}