// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace accomondationApp.AuthModel;

public partial class UserInRole
{
    public int UserInRolesId { get; set; }

    public int? RoleId { get; set; }

    public long? UserId { get; set; }

    public virtual Role Role { get; set; }

    public virtual LoginModel User { get; set; }
}