USE [master]
GO
/****** Object:  Database [hotelAppDB]    Script Date: 2024. 12. 17. 13:09:59 ******/
CREATE DATABASE [hotelAppDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'hotelAppDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\hotelAppDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'hotelAppDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\hotelAppDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [hotelAppDB] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [hotelAppDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [hotelAppDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [hotelAppDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [hotelAppDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [hotelAppDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [hotelAppDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [hotelAppDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [hotelAppDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [hotelAppDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [hotelAppDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [hotelAppDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [hotelAppDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [hotelAppDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [hotelAppDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [hotelAppDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [hotelAppDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [hotelAppDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [hotelAppDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [hotelAppDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [hotelAppDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [hotelAppDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [hotelAppDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [hotelAppDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [hotelAppDB] SET RECOVERY FULL 
GO
ALTER DATABASE [hotelAppDB] SET  MULTI_USER 
GO
ALTER DATABASE [hotelAppDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [hotelAppDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [hotelAppDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [hotelAppDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [hotelAppDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [hotelAppDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'hotelAppDB', N'ON'
GO
ALTER DATABASE [hotelAppDB] SET QUERY_STORE = OFF
GO
USE [hotelAppDB]
GO
/****** Object:  User [mihschmi]    Script Date: 2024. 12. 17. 13:09:59 ******/
CREATE USER [mihschmi] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  User [hoteldbuser]    Script Date: 2024. 12. 17. 13:09:59 ******/
CREATE USER [hoteldbuser] FOR LOGIN [hoteldbuser] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [mihschmi]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 2024. 12. 17. 13:09:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[customerId] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](250) NULL,
	[email] [nvarchar](200) NULL,
	[creationDate]  AS (getdate()),
PRIMARY KEY CLUSTERED 
(
	[customerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DisplayedMonth]    Script Date: 2024. 12. 17. 13:09:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DisplayedMonth](
	[displayedMonthId] [int] IDENTITY(1,1) NOT NULL,
	[displayedMonths] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[displayedMonthId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PaymentStatus]    Script Date: 2024. 12. 17. 13:09:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PaymentStatus](
	[paymentStatusId] [int] NOT NULL,
	[paymentStatus] [nvarchar](200) NOT NULL,
	[payed] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[paymentStatusId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PicturePath]    Script Date: 2024. 12. 17. 13:09:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PicturePath](
	[picturePathId] [int] IDENTITY(1,1) NOT NULL,
	[src] [nvarchar](250) NULL,
	[altText] [nvarchar](250) NULL,
	[slideId] [int] NULL,
	[roomId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[picturePathId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reservation]    Script Date: 2024. 12. 17. 13:09:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reservation](
	[reservationId] [int] IDENTITY(1,1) NOT NULL,
	[rommId] [int] NULL,
	[startDate] [date] NULL,
	[endDate] [date] NULL,
	[customerId] [int] NULL,
	[paymentStatusId] [int] NULL,
	[reservationDate]  AS (getdate()),
 CONSTRAINT [PK__Reservat__B14BF5C56D2F3B3C] PRIMARY KEY CLUSTERED 
(
	[reservationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Room]    Script Date: 2024. 12. 17. 13:09:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Room](
	[roomId] [int] IDENTITY(1,1) NOT NULL,
	[roomNumber] [nvarchar](250) NULL,
	[roomCapacityId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[roomId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RoomCapacity]    Script Date: 2024. 12. 17. 13:09:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RoomCapacity](
	[roomCapacityId] [int] NOT NULL,
	[capacity] [int] NULL,
 CONSTRAINT [PK__RoomCapa__FB83523FD0083160] PRIMARY KEY CLUSTERED 
(
	[roomCapacityId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Slides]    Script Date: 2024. 12. 17. 13:09:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Slides](
	[slideId] [int] NOT NULL,
 CONSTRAINT [PK__Slides__52D88E3FFD2EC7A6] PRIMARY KEY CLUSTERED 
(
	[slideId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PicturePath]  WITH CHECK ADD FOREIGN KEY([roomId])
REFERENCES [dbo].[Room] ([roomId])
GO
ALTER TABLE [dbo].[PicturePath]  WITH CHECK ADD  CONSTRAINT [FK__PicturePa__slide__2CF2ADDF] FOREIGN KEY([slideId])
REFERENCES [dbo].[Slides] ([slideId])
GO
ALTER TABLE [dbo].[PicturePath] CHECK CONSTRAINT [FK__PicturePa__slide__2CF2ADDF]
GO
ALTER TABLE [dbo].[Reservation]  WITH CHECK ADD  CONSTRAINT [FK__Reservati__custo__4316F928] FOREIGN KEY([customerId])
REFERENCES [dbo].[Customer] ([customerId])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Reservation] CHECK CONSTRAINT [FK__Reservati__custo__4316F928]
GO
ALTER TABLE [dbo].[Reservation]  WITH NOCHECK ADD  CONSTRAINT [FK__Reservati__payme__0C85DE4D] FOREIGN KEY([paymentStatusId])
REFERENCES [dbo].[PaymentStatus] ([paymentStatusId])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Reservation] NOCHECK CONSTRAINT [FK__Reservati__payme__0C85DE4D]
GO
ALTER TABLE [dbo].[Reservation]  WITH NOCHECK ADD  CONSTRAINT [FK__Reservati__rommI__44FF419A] FOREIGN KEY([rommId])
REFERENCES [dbo].[Room] ([roomId])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Reservation] NOCHECK CONSTRAINT [FK__Reservati__rommI__44FF419A]
GO
ALTER TABLE [dbo].[Room]  WITH NOCHECK ADD  CONSTRAINT [FK__Room__roomCapaci__0D7A0286] FOREIGN KEY([roomCapacityId])
REFERENCES [dbo].[RoomCapacity] ([roomCapacityId])
GO
ALTER TABLE [dbo].[Room] NOCHECK CONSTRAINT [FK__Room__roomCapaci__0D7A0286]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'it shows the number of beds' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'RoomCapacity', @level2type=N'COLUMN',@level2name=N'roomCapacityId'
GO
USE [master]
GO
ALTER DATABASE [hotelAppDB] SET  READ_WRITE 
GO
