// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace accomondationApp.Models;

public partial class DisplayedMonth
{
    public int DisplayedMonthId { get; set; }

    public int? DisplayedMonths { get; set; }
}