// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace accomondationApp.Models;

public partial class PicturePath
{
    public int PicturePathId { get; set; }

    public string Src { get; set; }

    public string AltText { get; set; }

    public int? SlideId { get; set; }

    public int? RoomId { get; set; }

    public virtual Room Room { get; set; }

    public virtual Slide Slide { get; set; }
}