// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace accomondationApp.Models;

public partial class RoomCapacity
{
    /// <summary>
    /// it shows the number of beds
    /// </summary>
    public int RoomCapacityId { get; set; }

    public int? Capacity { get; set; }

    public virtual ICollection<Room> Rooms { get; set; } = new List<Room>();
}