// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace accomondationApp.Models;

public partial class Room
{
    public int RoomId { get; set; }

    public string RoomNumber { get; set; }

    public int? RoomCapacityId { get; set; }

    public virtual ICollection<PicturePath> PicturePaths { get; set; } = new List<PicturePath>();

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();

    public virtual RoomCapacity RoomCapacity { get; set; }
}