// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace accomondationApp.Models;

public partial class Slide
{
    public int SlideId { get; set; }

    public virtual ICollection<PicturePath> PicturePaths { get; set; } = new List<PicturePath>();
}